export const LOAD_WMS_LAYER = 'LOAD_WMS_LAYER';
export const UNLOAD_WMS_LAYER = 'UNLOAD_WMS_LAYER';
export const LOAD_VECTOR_LAYER = 'LOAD_VECTOR_LAYER';
export const UNLOAD_VECTOR_LAYER = 'UNLOAD_VECTOR_LAYER';
